# Generated by Django 4.0.3 on 2022-04-02 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipe',
            old_name='created_at',
            new_name='criado_em',
        ),
    ]
