# Generated by Django 4.0.3 on 2022-04-03 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0002_rename_created_at_equipe_criado_em'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projeto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('criado_em', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('todo', 'Pendente'), ('done', 'Finalizada'), ('archived', 'Arquivada')], default='todo', max_length=20)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to=settings.AUTH_USER_MODEL)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='equipe.equipe')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='projeto.projeto')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
