# Generated by Django 4.0.3 on 2022-04-04 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0002_rename_created_at_equipe_criado_em'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projeto', '0002_tarefa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutos', models.IntegerField(default=0)),
                ('eh_registrado', models.BooleanField(default=False)),
                ('criado_em', models.DateField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to=settings.AUTH_USER_MODEL)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='equipe.equipe')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='projeto.projeto')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='projeto.tarefa')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
