# Generated by Django 4.0.3 on 2022-04-04 01:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0002_rename_created_at_equipe_criado_em'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projeto', '0003_registra'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registra',
            new_name='Registro',
        ),
    ]
