# Generated by Django 4.0.3 on 2022-04-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0006_alter_registro_criado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='segundos',
            field=models.IntegerField(default=0),
        ),
    ]
