# Generated by Django 4.0.3 on 2022-04-06 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0007_registro_segundos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='segundos',
        ),
    ]
