# Generated by Django 4.0.3 on 2022-04-06 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0008_remove_registro_segundos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='projeto.projeto'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='tarefa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='projeto.tarefa'),
        ),
    ]
